### ISSUE TITLE
Where The Data Path Setting?

### ISSUE THREAD

**Issue by wahello** [senssei/mongo-cluster-docker#17]
How to mount data volume to replication set.

**Comment by senssei** [comment]
@keyeMyria  If you want to have persistence - you can for example add manually add on each node (clusters and conf)
```
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
```

This was written from the top of my head, please verify and let me know, pull requests are very welcome :)

**Comment by ChenWes** [comment]
@senssei Hello, during the current test, the cluster Node data is saved, but when connected to the Mongos node, it is found that the data is not visible
